title: Daniil Luchin # your name (or website title) here
logo: "/images/photo1664133688.jpeg?raw=true" # your photo (or logo) here
description: |
  Experienced Data Analyst with a degree from the Higher School of Economics.
  
Experience:
  - duration: 2019-2021
    title: Data Scientist
    company: AG SPORTRADAR
    
  - duration: 2021-2023
    title: Business Analyst
    company: COEX

Skills:
  - Rstudio
  - Python
  - HTML/CSS
  - Power BI
  - Excel

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# google_analytics: UA-000000-0 # Uncomment and add your Google Analytics tracking ID here
